version: "3.9"

services:
  backend:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - HOST=db
      - USER=root
      - PASS=PJxsisJwMq7DYVi
      - DB=odontologia
      - SECRET_JWT=eqm3PJgdoXeXO2vQkRWm
      - SECRET_SESSION=kTs7wfZt09s6GXwDXHv1
      - PORT=5000
    depends_on:
      - db
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: PJxsisJwMq7DYVi
      MYSQL_DATABASE: odontologia
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  db_data:
