GET http://localhost:3000/turnos
Cookie: session=eyJ0b2tlbiI6ImV5SmhiR2NpT2lKSVV6STFOaUlzSW5SNWNDSTZJa3BYVkNKOS5leUpwWkNJNk5Dd2ljbTlzWlNJNkltUnZZM1J2Y2lJc0ltbGhkQ0k2TVRjME1URXdPREExT0gwLllGUmdNSG9PclA1SUlrOEhZeWhCYV9wRHVyX3NzbTE4UVFJb2gwVERXc3MifQ==


###

GET http://localhost:3000/turnos/1


###
POST http://localhost:3000/turnos
Content-Type: application/json
Cookie: session=eyJ0b2tlbiI6ImV5SmhiR2NpT2lKSVV6STFOaUlzSW5SNWNDSTZJa3BYVkNKOS5leUpwWkNJNk5Dd2ljbTlzWlNJNkltUnZZM1J2Y2lJc0ltbGhkQ0k2TVRjME1URXdPREExT0gwLllGUmdNSG9PclA1SUlrOEhZeWhCYV9wRHVyX3NzbTE4UVFJb2gwVERXc3MifQ==

{
  "dia_turno": "2025-03-02",
  "hora_turno": "10:40:00",
  "nombre_completo": "Juan Pérez",
  "fecha_nacimiento": "1990-05-15",
  "sexo": "Masculino",
  "dni": "12345678",
  "cobertura": "Particular",
  "telefono": "123456789",
  "email": "juan.perez@example.com",
  "motivo_consulta": "Chequeo general",
  "nro_historial_clinico": "HC12345"
}



###

DELETE http://localhost:3000/turnos
Content-Type: application/json

{
  "id":6
}


###

GET https://odontologia-back.onrender.com/turnos


###

POST https://odontologia-back.onrender.com/turnos
Content-Type: application/json


{
  "dia_turno": "2025-02-01",
  "hora_turno": "10:30:00",
  "nombre_completo": "Juan Pérez",
  "fecha_nacimiento": "1990-05-15",
  "sexo": "Masculino",
  "dni": "12345678",
  "cobertura": "Particular",
  "telefono": "123456789",
  "email": "juan.perez@example.com",
  "motivo_consulta": "Chequeo general",
  "nro_historial_clinico": "HC12345",
  "nombre_completo_titular": "Maria Pérez",
  
  "nro_afiliado": "AF1234567",
  "nombre_obra_social": "Obra Social XYZ"
}



### 


GET http://localhost:3000/pacientes

### 

POST http://localhost:3000/pacientes
Content-Type: application/json

{
  "nombre":"raul",
  "apellido":"lopez",
  "dni":"44000001",
  "telefono":"1122334455",
  "email":"pepe@pepe.com",
  "obra_social":"particular",
  "notas_adicionales":"notas adicionales"
}

###

POST http://localhost:3000/usuarios/register
Content-Type: application/json
Cookie: session=eyJ0b2tlbiI6ImV5SmhiR2NpT2lKSVV6STFOaUlzSW5SNWNDSTZJa3BYVkNKOS5leUpwWkNJNk5Dd2ljbTlzWlNJNkltUnZZM1J2Y2lJc0ltbGhkQ0k2TVRjME1URXdPREExT0gwLllGUmdNSG9PclA1SUlrOEhZeWhCYV9wRHVyX3NzbTE4UVFJb2gwVERXc3MifQ==

{
  "nombre":"usuario",
  "email":"test@test.com",
  "password":"test",
  "role":"doctor"

}

###
POST http://localhost:3000/usuarios/login
Content-Type: application/json

{
  "email":"test@test.com",
  "password":"test"
}